[package]
name = "ferrunitas"
version = "0.3.0"
edition = "2024"
rust-version = "1.85.0"
authors = ["Marek Hummel <marek.hummel3@gmail.com>"]
description = "A type-safe unit conversion library with compile-time dimensional analysis"
license = "Apache-2.0"
repository = "https://github.com/marekhummel/ferrunitas"
documentation = "https://docs.rs/ferrunitas"
readme = "README.md"
keywords = ["units", "conversion", "measurement", "SI", "dimensional-analysis"]
categories = ["science", "data-structures", "mathematics", "value-formatting"]
exclude = ["/.github/", "system_test.rs"]

[profile.release]
lto = "fat"

[lints.rust]
missing_docs = "warn"

[lib]
name = "ferrunitas"
path = "src/lib.rs"


[features]
default = ["std", "f64"]
std = ["num-traits/std", "serde?/std", "approx?/std"]
quantity_tags = []
serde = ["dep:serde"]
approx = ["dep:approx"]

f64 = []
f32 = []


[[example]]
name = "serialization"
required-features = ["serde"]

[dependencies]
const_format = "0.2.34"
num-traits = { version = "0.2.19", default-features = false }
typenum = "1.18.0"
paste = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
approx = { version = "0.5.1", default-features = false, optional = true }

[dev-dependencies]
serde_json = "1.0.143"
