name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit from tag
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install toml-cli
        run: cargo install toml-cli

      - name: Check tag version matches cargo toml version
        run: test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"

      - name: Run tests (just to be sure)
        run: |
          cargo test --no-default-features --features f64 --verbose
          cargo test --features "serde approx quantity_tags" --verbose

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
